### PR TITLE
Drop support for legacy Python 2.7

### LINKED ISSUE #497: Drop python 2.7 support
its about time...

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #497.

Adds `python_requires` to help pip.

Also upgrade syntax with https://github.com/asottile/pyupgrade.

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
Wow did not expect somebody to support us that quickly. Thank you @hugovk 

I fixed the merge conflict. 

While you are at it, do you want to add a batch / configure travis for python 3.6?

**Comment by hugovk** [comment]
You're welcome!

> While you are at it, do you want to add a batch / configure travis for python 3.6?

Done! I also updated pytest and its plugins because there was a version conflict:

```
0.37s$ if [ $TRAVIS_PULL_REQUEST == false ] && ! [ $TRAVIS_BRANCH == 'master' ]; then pytest tests/units -n2; else pytest tests; fi
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 3.3.0 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.6.0'))
```

**Comment by MaxBenChrist** [comment]
I did not forget this. I will add a deprication warning under python 2.7, and then release one last version  (0.11.3) of tsfresh with python 2.7 support.

In the new minor version line 0.12.* I want to proceed without python 2, will therefore merge this pr as soon as we released 0.11.3. Thanks again for the help 👍

**Comment by hugovk** [comment]
Hmm, the rebase to resolve conflict didn't go so smoothly, the CI is failing. Let me know when the last version supporting 2.7 is out, and I'll redo it. Thanks!

**Comment by Froskekongen** [comment]
TBH, I think dropping support for python3.5 also makes sense: https://www.python.org/dev/peps/pep-0478/

**Comment by MaxBenChrist** [comment]
> TBH, I think dropping support for python3.5 also makes sense: https://www.python.org/dev/peps/pep-0478/

can you elaborate why you think that we should do that?

**Comment by Froskekongen** [comment]
Most OSes now have python 3.6 or 3.7 as default versions (including Ubuntu 18.04 and MacOS, which most people using this package are using). Removing support for older versions allows for more progressive updates of the software, imo, and also makes it possible to integrate new features more easily.

I think the real question is rather, why have support for 3 python versions (3.5, 3.6 and 3.7), when only marginal number of users use 3.5 (and they should probably upgrade as well).

Allowing for 3.6+ also makes it possible to use type hints and mypy, which in my experience can improve testing and software quality significantly.

**Comment by nils-braun** [comment]
This PR is superseeded by #568 including all the changes. I am therefore closing it.

**Pull request closed without merging**
