### PR TITLE
Multiclass

### PR DESCRIPTION
**Pull request by kartikey-vyas**
Implements feature selection for multiclass classification problems, by setting the new parameter `multiclass = True`. 

e.g. `X_filt = select_features(X, y, multiclass = True, n_significant = 2, ml_task = 'classification')`

It uses a one vs. rest scheme to conduct hypothesis tests for each class in the target vector. Relevance is determined by the number of classes for which a feature is a significant predictor. The parameter `n_significant` can be adjusted to change the stringency of the relevance filter. For example, in a four-class classification problem, with parameters `multiclass = True, n_significant=3`, features would have to pass hypothesis tests for at least 3 classes in order to be selected. This is in contrast with the current implementation, which would accept features which are relevant for determining just 1 class.

The adapted code passes all existing unit tests and additional tests have been written to verify the functionality of the multiclass code.

functions/classes edited:
- `tsfresh.feature_selection.relevance.calculate_relevance_table`
- `tsfresh.feature_selection.selection.select_features`
- `tsfresh.transformers.feature_selector.FeatureSelector`

I have been working with Andreas at the University of Auckland, we have produced this contribution as a part of another project which required the use of tsfresh for a multiclass classification problem.

### CODE REVIEW

**Comment by nils-braun** [comment]
First of all: thank you very much for your very nice PR. We are always happy for contributions!

Sorry I did not answer already on the PR. You can ignore the problem with the failing benchmark test. The problem is, that so far the test is not working if you do a PR from a forked repository. Sorry for the confusion, I should definitely disable the test.

Concerning the pycov tests: these tests check, how large your test coverage is (how much of your code is tested). They are not a hard requirement and we do allow pull requests with failing coverage requirement, but in principle it would be nice if your code has the same test coverage as the rest of the package. Currently, your newly introduced code has a coverage of 92% whereas the rest has 95%. This is close enough for us to accept, but if you have any idea on how to increase it we are of course happy :-)

I will try to find some time to look into your PR this week.

**Review by nils-braun — COMMENTED** [review]
Very nice! Thank you very much again for your PR. I do have some (mostly cosmetical) comments, but in general I am fine with this. 

Would you also like to add your new parameters to the function `extract_relevant_features`?

**Comment by nils-braun** [comment]
And last comment: if you merge "main" into your PR the failing test should also be gone :-)

**Comment by kartikey-vyas** [comment]
Hi Nils,

Thank you very much for reviewing my PR! I will address each of these
issues in the coming days. I appreciate the time you spent on this.

Cheers
Kartikey

**Comment by kartikey-vyas** [comment]
Hi Nils, I've made some changes to try and address the comments that you raised. I think a potential limitation of using a one vs. rest approach as I have done during hypothesis testing is that the Mann-Whitney U test will designate certain features as irrelevant that would be strong predictors under a one vs. one scheme. I hope to implement this as a new option in an additional PR.

**Comment by nils-braun** [comment]
Thank you so much @kartikey-vyas and sorry (again!) it took so long to get a reaction from me. I am quite busy currently :-/
Very nice contribution!

**Pull request merged**
