### PR TITLE
Apply python package "black" to tsfresh repo

### PR DESCRIPTION
**Pull request by mendel5**
Related to
- Issue: https://github.com/blue-yonder/tsfresh/issues/820
- Previous pull request: https://github.com/blue-yonder/tsfresh/pull/858

I applied the python package [black](https://github.com/psf/black) to the tsfresh repository.

This is the output from my terminal:
```
$ black tsfresh/
reformatted tsfresh/tests/integrations/examples/test_har_dataset.py
reformatted tsfresh/tests/integrations/test_bindings.py
reformatted tsfresh/tests/benchmark.py
reformatted tsfresh/tests/integrations/examples/test_robot_execution_failures.py
reformatted tsfresh/docs/conf.py
reformatted tsfresh/tests/integrations/test_full_pipeline.py
reformatted tsfresh/tests/integrations/test_notebooks.py
reformatted tsfresh/tests/integrations/examples/test_driftbif_simulation.py
reformatted tsfresh/tests/integrations/test_relevant_feature_extraction.py
reformatted tsfresh/tests/units/feature_selection/test_checks.py
reformatted tsfresh/tests/integrations/test_feature_extraction.py
reformatted tsfresh/tests/units/feature_selection/test_fdr_control.py
reformatted tsfresh/tests/fixtures.py
reformatted tsfresh/tests/units/feature_extraction/test_settings.py
reformatted tsfresh/tests/units/feature_extraction/test_extraction.py
reformatted tsfresh/tests/units/scripts/test_run_tsfresh.py
reformatted tsfresh/tests/units/feature_selection/test_significance_tests.py
reformatted tsfresh/tests/units/transformers/test_feature_augmenter.py
reformatted tsfresh/tests/units/feature_selection/test_relevance.py
reformatted tsfresh/tests/units/utilities/test_string_manipilations.py
reformatted tsfresh/tsfresh/__init__.py
reformatted tsfresh/tests/units/feature_selection/test_feature_significance.py
reformatted tsfresh/tests/units/feature_extraction/test_data.py
reformatted tsfresh/tsfresh/examples/__init__.py
reformatted tsfresh/tsfresh/convenience/bindings.py
reformatted tsfresh/tests/units/transformers/test_relevant_feature_augmenter.py
reformatted tsfresh/tests/units/transformers/test_per_column_imputer.py
reformatted tsfresh/tsfresh/feature_extraction/__init__.py
reformatted tsfresh/tsfresh/convenience/relevant_extraction.py
reformatted tsfresh/tsfresh/examples/har_dataset.py
reformatted tsfresh/tests/units/utilities/test_distribution.py
reformatted tsfresh/tsfresh/examples/robot_execution_failures.py
reformatted tsfresh/tsfresh/examples/driftbif_simulation.py
reformatted tsfresh/tsfresh/feature_extraction/extraction.py
reformatted tsfresh/tsfresh/feature_selection/significance_tests.py
reformatted tsfresh/tsfresh/scripts/run_tsfresh.py
reformatted tsfresh/tsfresh/scripts/test_timing.py
reformatted tsfresh/tsfresh/feature_extraction/data.py
reformatted tsfresh/tsfresh/scripts/measure_execution_time.py
reformatted tsfresh/tsfresh/transformers/feature_augmenter.py
reformatted tsfresh/tsfresh/transformers/per_column_imputer.py
reformatted tsfresh/tsfresh/feature_extraction/settings.py
reformatted tsfresh/tsfresh/utilities/profiling.py
reformatted tsfresh/tsfresh/utilities/string_manipulation.py
reformatted tsfresh/tsfresh/transformers/relevant_feature_augmenter.py
reformatted tsfresh/tsfresh/utilities/distribution.py
reformatted tsfresh/tsfresh/utilities/dataframe_functions.py
reformatted tsfresh/tests/units/utilities/test_dataframe_functions.py
reformatted tsfresh/tests/units/feature_extraction/test_feature_calculations.py
reformatted tsfresh/tsfresh/feature_extraction/feature_calculators.py
All done! ✨ 🍰 ✨
50 files reformatted, 21 files left unchanged.
```

Please review and also have a look at [this image](https://imgur.com/a/waLE2kW).

### CODE REVIEW

**Comment by mendel5** [comment]
Hi @MaxBenChrist and @nils-braun , did you already take a look at this?

**Comment by nils-braun** [comment]
Hi @mendel5! Thanks for the PR, the nice image (I like!) and for the second ping.

Your changes do look good, but interfere a bit with the pycodestyle we already have. That is not a big issue and I will try to incorporate "black" into the automatic style checking next. This PR is ready for merging!

**Comment by mendel5** [comment]
> This PR is ready for merging!

Thanks!

> Your changes do look good, but interfere a bit with the pycodestyle we already have. That is not a big issue and I will try to incorporate "black" into the automatic style checking next.

Is this the same thing you mentioned [here](https://github.com/blue-yonder/tsfresh/pull/858#issuecomment-860051887) before? See:
> I can help you with implementing a git-hooks setting for black (and, while doing so, maybe even isort).

How can I help with this? Please tell me!

**Comment by nils-braun** [comment]
Sorry, I was too quick :-(

Please see the referenced PR.
All i did was to install pre-commit and add some configuration. With that, all developers of tsfresh will automatically use the correct styling etc. while committing.

**Comment by mendel5** [comment]
> Sorry, I was too quick :-(

No worries, it's okay.

> Please see the referenced PR.

- https://github.com/blue-yonder/tsfresh/pull/876
- https://github.com/blue-yonder/tsfresh/commit/b9a7b188221eeeaa1dede4739f7fc55b8e1feeeb
- https://github.com/blue-yonder/tsfresh/commit/ff69073bbb4df787fcbf277a611c6b40632e767d

I will close the original issue at https://github.com/blue-yonder/tsfresh/issues/820 now.

If you need anything else from me, please let me know.

**Pull request merged**
