### PR TITLE
Add root mean square feature

### PR DESCRIPTION
**Pull request by OliEfr**
#811 

I added the feature and unit tests. I build the docs.

Before I changed anything in the code already four unit tests failed. I am not sure how to handle this.

After I made my changes some more tests failed -in `tests.integrations.test_feature_extraction`:
I assume, this is because adding a new features changes the df dimensions. Should I adjust them?

### CODE REVIEW

**Review by nils-braun — COMMENTED** [review]
First of all: thanks a lot for your PR :-) In general I am quite ok with the changes in the feature calculators. I will now check the failing tests!

You did commit a few files that should not be there (the dask-worker space files and the pipeline file). If you want you can also add some entries in the .gitignore file to prevent this from happening!

**Comment by nils-braun** [comment]
So, concerning the test failures:
* tests/integrations/test_feature_extraction.py::FeatureExtractionTestCase::test_dask abd  tests/integrations/test_feature_extraction.py::FeatureExtractionTestCase::test_dask_no_pivot: that might be because you accidentally committed the two dask worker files
* tests/integrations/test_feature_extraction.py::FeatureExtractionTestCase::test_pandas, tests/integrations/test_feature_extraction.py::FeatureExtractionTestCase::test_pandas_no_pivot and tests/units/feature_extraction/test_settings.py::TestMinimalSettingsObject::test_extraction_runs_through: as your feature is also part of the simple and minimal features, you will need to add your feature to the output results in these tests (as you have pointed out)
* tests/units/feature_extraction/test_feature_calculations.py::FeatureCalculationTestCase::test_root_mean_square
that is your own new feature :-) You need to convert the input to a numpy array before you can use it (as `**` is only defined on numpy arrays, not on lists). You can use `np.asarray` for example, as in longest_strike_below_mean.
* tests/units/transformers/test_relevant_feature_augmenter.py::test_relevant_augmentor_cross_validated: also affected by your new feature :-)
* tests/units/utilities/test_dataframe_functions.py::RollingTestCase::test_warning_on_non_uniform_time_steps: that one needs fixing from my side. I will open a new PR to fix this.

Which other tests did fail for you before you added the feature?

**Comment by OliEfr** [comment]
Thanky, I'll keep working on it!

When I run the test and commited all .coverage files where added as well. Obviously I dont want that.
Why arent these files included in the gitignore? And how do I know which filetypes I should exclude?

**Comment by nils-braun** [comment]
There is no good reason to not have those files added to .gitignore (other than: we just forgot to do it). 
In general: it is a good idea to not add any new files to your PR - if you did not create these files intentionally the chances are high you do not want to commit them.
Or put it the other way round: only add files to your commits and PRs that you edited intentionally.
But yes, lets add those files to the .gitignore. Would you like to do a PR or shall I do it?

**Comment by OliEfr** [comment]
Thats a good point.
Let me do the PR :)

**Comment by OliEfr** [comment]
Okay I think I resolved all failing tests which were on my watch - thanks for the help :)

**Comment by nils-braun** [comment]
Thanks! I have fixed the errors also on the main branch. Feel free to merge it back in.

**Comment by OliEfr** [comment]
It failt in 'test_relevant_augmentor_cross_validated'.
I dont know how to resolve.

**Comment by nils-braun** [comment]
Depending on which IDE you are using, most modern IDEs come with nice support for showing test results. For example I am using VSCode together with the "Python Test Explorer for Visual Studio Code" extension - that works quite well if you want a "GUI".

Concerning the failing tests: I think we are triggering an incompatibility in scikit-learn here. I have created #822 to bump the scikit-learn version to 0.22 (which is ok, as this is already some years old). At least for me this solves the issue. Would you like to test again once the branch is merged?

By the way: I am planning to do a new release of tsfresh end of this week. There is no need to hurry (as there will be definitely another release), just for your information!

**Comment by OliEfr** [comment]
I installed the extension and will try it next time :)

Thanks for fixing the version-issue - I would have never gotten this idea! Works now.

**Comment by nils-braun** [comment]
Cool! Thanks for your contribution!

**Pull request merged**
