### PR TITLE
add benjamini-yekutieli procedure

### PR DESCRIPTION
**Pull request by smueller18**
Add a notebook that plots the benjamini-yekutieli procedure.
This addresses the use case described in #216.

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
Looks good. 

- Maybe you could add some text fields describing what we see in the plot
- Also, you could add "plt.show()" calls to the end of the plotting cells

**Comment by nils-braun** [comment]
@smueller18 Do you want to do the changes or shall we implement it?

**Comment by smueller18** [comment]
I will extend the notebook after my exams, currently I have no time. I will comment when the example is ready to pull.

**Comment by MaxBenChrist** [comment]
@smueller18 will you update that notebook soon?

**Comment by smueller18** [comment]
I close it for the moment and will edit and reopen it after my vacation.

**Comment by smueller18** [comment]
Please have a look at the extended notebook

**Comment by MaxBenChrist** [comment]
looks good. What I am missing is a cell at the top that explains the purpose of the notebook.

**Comment by MaxBenChrist** [comment]
I will comment the notebook by myself

**Pull request merged**
