### PR TITLE
Merge pr #140 into feature_extraction_settings_refacturing

### PR DESCRIPTION
**Pull request by kempa-liehr**

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
Is the title really fitting? I am confused about which merge conflict is solved here.

The changes to the driftbif dataset look fine to me. I would merge them

**Comment by kempa-liehr** [comment]
@MaxBenChrist, you're right and I've changed the title of the pr. 
It was my _working title_, because it started as merge conflicts, when I switched #87 from master to feature_extraction_settings_refacturing.

**Comment by kempa-liehr** [comment]
Is there a plan for merging feature_extraction_settings_refacturing into master?

**Comment by MaxBenChrist** [comment]
We still have to change a few things. 

Also, the settings_refacturing is quite a radical change of the public APIs. We have to make sure that we provide enough examples so users can switch easily. I do not have the time at the moment to provide those examples.

**Pull request merged**
