### PR TITLE
Changed constructed id in roll_time_series from string to tuple

### PR DESCRIPTION
**Pull request by TKlerx**
As discussed in #699 I changed the construction of the new id in roll_time_series from string to tuple. 
Also wrote a testcase to test whether the sorting really works as intended on `column_sort` if the column is integer containing integers of different length (number of digits).

### CODE REVIEW

**Comment by TKlerx** [comment]
Do you know why this fails for pandas v0.20.3?
The failures do not make sense to me.

**Comment by nils-braun** [comment]
@TKlerx I can only guess, but I think in this older version of pandas the logic to have a multi dimensional cell was not well supported.
What I think it does: the dataframe has actually 4 columns (id, kind, time, value) and just a single row (at least when it fails). The apply should create a single entity, which is a 2-tuple. pandas tries to match this 2-tuple with the 4 columns (which is obviously wrong). Do not ask me why it does so...

But, it can be fixed :-)
By moving the `[column_id]` to the dataframe before applying, you turn it into a series and no confusion is possible:
```python
df_temp["id"] = df_temp[column_id].apply(lambda row: (row, timeshift_value))
```
I just did a quick test with this old pandas version and it seems to work properly.

**Comment by nils-braun** [comment]
Looks good to me @TKlerx! Thanks for working on this.

Before we merge this, we would need to fix the documentation for the rolling/forecasting (both the docstrings, although the should be mostly fine already and the sphinx docu). Would you like to work on this or shall I propose a change?

**Comment by TKlerx** [comment]
Should be done, I guess. Could you please check that I did not miss anything?

**Comment by nils-braun** [comment]
Very good! Thanks for your contribution.

**Comment by HaveF** [comment]
hi, @nils-braun 
Do we have any plan to release this feature?
I see this on latest doc, but it seems  not release on code.

**Comment by nils-braun** [comment]
Yes, it is in the latest master version that you can install via pip install -e git+https://github.com/blue-yonder/tsfresh.

You are right however, that it is not (yet) in a properly released version. We are still discussing on some internal details on some other topics (see the currently open PRs) which I would love to have fixed before we do the next release. 
Is installation from source (or as I have shown above) no option for you?

**Comment by HaveF** [comment]
@nils-braun Thanks. Just a bit curious the out of sync about the doc and code. Git version is fine. Thanks again.

**Comment by nils-braun** [comment]
Ok! We (and many other projects) do have multiple versions of the documentation. The "latest" always shows the current main branch - here it is included (both in code and docu). Then there is "stable", which is the last released version (0.16.0 in our case). Here, the docu still shows the old format (because, as you correctly stated, it is not in the last release). And then there is of course documentation for every released version.

If you want to only get the documentation of your installed tsfresh version, you should make sure that you choose the correct version of the docs also.

**Pull request merged**
