### PR TITLE
Implement approximate entropy algorithm

### PR DESCRIPTION
**Pull request by CYHSM**
Information about this algorithm : [Approximate Entropy](https://en.wikipedia.org/wiki/Approximate_entropy) 

Also see [this](https://www.ncbi.nlm.nih.gov/pubmed/10843903?dopt=Abstract) paper for some limtations and similar algorithms which could also be implemented as a new feature in tsfresh.

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
Nice work! Unfortunately, our unit tests are failing. Can you look into that?

Do you want to implement the features from the "Physiological time-series analysis using approximate entropy and sample entropy" paper as well?

**Comment by MaxBenChrist** [comment]
[Here](http://tsfresh.readthedocs.io/en/latest/text/how_to_contribute.html) you can find an instruction how to run the tests locally.

**Comment by CYHSM** [comment]
Ah i see, sorry! I will look into it!

**Comment by MaxBenChrist** [comment]
Perfect! And while you are on it, it would be great if you could also add some unit tests for your new feature calculator.

If you need some help, let us know

**Comment by CYHSM** [comment]
Ok i looked into it. Took me some time to figure this out. (is there an easier way to debug pytest instead of using stdout?) 

So maybe for others it should be made more clear that some tests pass sliced panda.Series to the functions so the keys do not always start at 0 (this can be resolved with `pd_series.reset_index(drop=True)` or `x = np.asarray(x)`)

Also i'm curious, why not make numpy array the standard input?

**Comment by MaxBenChrist** [comment]
Hi @CYHSM great addition. 👍  I will merge this pr during the next days. Before merging, I will think about this _phi function. Maybe I can find a way to vectorize it

**Comment by CYHSM** [comment]
I tried vectorizing the rest. It works with: 
```
x_re = np.array(np.squeeze(np.split(np.tile(x, [1, N-m+1]),
                         np.insert(np.arange(m, (N+1)*(N-m+1)+m, step=N+1),
                         np.arange(N-m+1),
                         np.arange(0, (N+1)*(N-m+1), step=N+1)), axis=1)[1::2]))
```
but its slower in the end because you have to create a NxN matrix or an array with size N^2.  

I removed one of the loops and replaced it with indexing: 
`np.array([x[i:i+m] for i in range(N - m + 1)])`
This gives another speed boost!

**Comment by MaxBenChrist** [comment]
Awesome, the first feature calculator that was contributed.

You want to solve that merge conflict? ( you just have to move your feature calculator settings to the init method of the FeatureExtractionSettings Object)

**Comment by CYHSM** [comment]
Yay. Finally (:

**Comment by MaxBenChrist** [comment]
I think you reversed the last commit on master bf9e830

**Comment by MaxBenChrist** [comment]
So close! 😂 I can fix this later

**Comment by CYHSM** [comment]
Oh sorry. What should i do? :grimacing:

**Comment by MaxBenChrist** [comment]
fixed it in 8048ef4

**Pull request merged**
