### PR TITLE
Fix parameter sorting

### PR DESCRIPTION
**Pull request by trueckel**
This shall fix issue #635

### CODE REVIEW

**Comment by nils-braun** [comment]
Thank you very much for the PR, but our tests also rely on the extracted parameter names. Would you mind also fixing them?

**Comment by nils-braun** [comment]
@trueckel Should I fix the tests or do you need help in any way for this?

**Comment by trueckel** [comment]
@nils-braun I am a bit clueless regarding the tests, so I would prefer if you would do it.

**Comment by nils-braun** [comment]
Superseeded by #656 with added tests.

**Pull request closed without merging**
