### PR TITLE
MAINT Remove pyscaffold build dependency

### PR DESCRIPTION
**Pull request by rth**
Closes https://github.com/blue-yonder/tsfresh/issues/486

This removes the pyscaffold build dependency and generally updates the `setup.py`. The  `README.rst` is also no longer necessary I think as PyPi can now render markdown.

This adds `setuptools_scm` as a setup depdendency though as was (indirectly) suggested in #486

### CODE REVIEW

**Comment by rth** [comment]
Currently  Travis CI fails with,
```
if [ $TRAVIS_PULL_REQUEST == false ] && ! [ $TRAVIS_BRANCH == 'master' ]; then py.test tests/units -n2; else python setup.py test; fi
/home/travis/build/blue-yonder/tsfresh/.eggs/setuptools_scm-3.2.0-py3.5.egg/setuptools_scm/git.py:68: UserWarning: "/home/travis/build/blue-yonder/tsfresh" is shallow and may cause errors
  warnings.warn('"%s" is shallow and may cause errors' % (wd.path,))
running test
error: error in setup.cfg: command 'test' has no such option 'addopts'
```

the first warning is due to https://github.com/pypa/setuptools_scm/issues/93


For the second I'm going to replace,
```
python setup.py test
```
by
```
pytest tests
```
directly, as the former is somewhat deprecated as far as I know and doesn't allow using any of the useful pytest options.

**Comment by rth** [comment]
> Please copy all content from setup.cfg to into the `setup()` call [in `setup.py`]

Why? This is supported by setuptools since 2016 and is independent of the use of `pyscaffold` (https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files) . As mentioned by setuptools docs,

> This approach not only allows automation scenarios but also reduces boilerplate code in some cases.

**Comment by rth** [comment]
Otherwise the CI failures appear to be the same as those on master..

**Comment by MaxBenChrist** [comment]
Sorry, have been extremely busy the last weeks. Thanks for helping with this. 

The error looks unrelated to this pr, could be a change in a newer dask/pandas version

**Comment by MaxBenChrist** [comment]
I will try to look into the failing unit test later

**Comment by MaxBenChrist** [comment]
Thanks for taking care of this 👍

**Pull request merged**
