### PR TITLE
Conda

### PR DESCRIPTION
**Pull request by nils-braun**
Added support for anaconda to upload here:
http://anaconda.org/nbraun/tsfresh/

### CODE REVIEW

**Comment by nils-braun** [comment]
The conda upload is now only done on git tags - as also the pipy upload.

**Comment by MaxBenChrist** [comment]
As discussed, we should get a non personal account. maybe tsfresh/tsfresh or blue-yonder/tsfresh

**Comment by nils-braun** [comment]
I will fix the merge conflict once the speed up PR is in.

**Comment by nils-braun** [comment]
I think this PR can now be closed, as we will handle this using conda forge.

**Pull request closed without merging**
