### PR TITLE
Change double quotes to single quotes for main directory

### PR DESCRIPTION
**Pull request by mendel5**
Related to https://github.com/blue-yonder/tsfresh/issues/820

Use single quotes instead of double quotes

Directory: `tsfresh/`

### CODE REVIEW

**Comment by nils-braun** [comment]
Hi @mendel5 - thanks for starting to work on this! Really appreciated. 
As I mentioned in the issue, I am happy to have this change. However, I would again strongly advocate for an automated solution using one of the "typical" python tools: black (preferred) or any other tool. Otherwise, I fear that you will need to repeat this work quite often...

**Comment by mendel5** [comment]
> I would again strongly advocate for an automated solution

Ok, so 'black' is this one https://github.com/psf/black , right? MaxBenChrist also recommended https://github.com/edaniszewski/pylint-quotes .

Should I just apply one of these tools to the whole repo and create a pull request? Or what do you think is the best approach?

Btw I would like to use https://github.com/edaniszewski/pylint-quotes#configuration with this config:
```
string-quote=single
triple-quote=single
docstring-quote=double
```
Would that be ok for you?

**Comment by nils-braun** [comment]
> Should I just apply one of these tools to the whole repo and create a pull request? Or what do you think is the best approach?

Yes, I think that would be the best approach. Thanks!

Your link to black ja correct, but pylint is also fine! Thanks!

**Comment by mendel5** [comment]
> Yes, I think that would be the best approach.

Today I found the time to apply [pylint-quotes](https://github.com/edaniszewski/pylint-quotes) to the tsfresh repo.

The output of `pylint-quotes` spans about 5760 lines. The funniest part is the final line:
```
Your code has been rated at -1.09/10 (previous run: -1.09/10, +0.00)
```
I didn't know `pylint-quotes` was able to give a negative rating.

I actually expected `pylint-quotes` to not only analyze the code and give recommendations but to also be able to transform the code and apply its own recommendations. It seems that all of the recommendations by `pylint-quotes` have to be implemented manually.

Maybe [autopep8](https://github.com/hhatto/autopep8) is a possible alternative for auto-formatting? Although it might not be necessary because https://github.com/blue-yonder/tsfresh/pull/607 should have already made tsfresh compliant with [pep8](https://www.python.org/dev/peps/pep-0008/). What do you think?

**Comment by nils-braun** [comment]
Ouch, well that is definitely a blocker then - we should not implement this manually!

The code is pep8 compatible (we even [test](https://github.com/blue-yonder/tsfresh/blob/main/.github/workflows/stylecheck.yml) this on every PR), but as discussed, PEP8 does not make any suggestion on the quotes, so `pycodestyle` will unfortunatley not complain...

Sorry to repeat myself :-), but I would still like to suggest black. It has both a check-mode and a fix-mode. It does more than just fixing the quotes, but I know that many developers are already used to the black code style. @MaxBenChrist, @mendel5 - if you are fine with that I would suggest to use black. I can help you with implementing a `git-hooks` setting for black (and, while doing so, maybe even `isort`).

**Comment by mendel5** [comment]
Hi @nils-braun , today I applied the Python package "black" to tsfresh.

Here is the output from my terminal:
```
$ black tsfresh-black/
reformatted tsfresh-black/tests/integrations/examples/test_har_dataset.py
reformatted tsfresh-black/tests/integrations/test_bindings.py
reformatted tsfresh-black/tests/benchmark.py
reformatted tsfresh-black/tests/integrations/examples/test_robot_execution_failures.py
reformatted tsfresh-black/docs/conf.py
reformatted tsfresh-black/tests/integrations/test_full_pipeline.py
reformatted tsfresh-black/tests/integrations/test_notebooks.py
reformatted tsfresh-black/tests/integrations/examples/test_driftbif_simulation.py
reformatted tsfresh-black/tests/integrations/test_relevant_feature_extraction.py
reformatted tsfresh-black/tests/units/feature_selection/test_checks.py
reformatted tsfresh-black/tests/integrations/test_feature_extraction.py
reformatted tsfresh-black/tests/units/feature_selection/test_fdr_control.py
reformatted tsfresh-black/tests/fixtures.py
reformatted tsfresh-black/tests/units/feature_extraction/test_settings.py
reformatted tsfresh-black/tests/units/scripts/test_run_tsfresh.py
reformatted tsfresh-black/tests/units/feature_extraction/test_extraction.py
reformatted tsfresh-black/tests/units/feature_selection/test_significance_tests.py
reformatted tsfresh-black/tests/units/transformers/test_feature_augmenter.py
reformatted tsfresh-black/tests/units/feature_selection/test_relevance.py
reformatted tsfresh-black/tests/units/utilities/test_string_manipilations.py
reformatted tsfresh-black/tsfresh/__init__.py
reformatted tsfresh-black/tsfresh/convenience/bindings.py
reformatted tsfresh-black/tests/units/feature_extraction/test_data.py
reformatted tsfresh-black/tests/units/transformers/test_relevant_feature_augmenter.py
reformatted tsfresh-black/tsfresh/examples/__init__.py
reformatted tsfresh-black/tests/units/transformers/test_per_column_imputer.py
reformatted tsfresh-black/tests/units/utilities/test_distribution.py
reformatted tsfresh-black/tsfresh/feature_extraction/__init__.py
reformatted tsfresh-black/tsfresh/convenience/relevant_extraction.py
reformatted tsfresh-black/tsfresh/examples/har_dataset.py
reformatted tsfresh-black/tests/units/feature_selection/test_feature_significance.py
reformatted tsfresh-black/tsfresh/examples/robot_execution_failures.py
reformatted tsfresh-black/tsfresh/examples/driftbif_simulation.py
reformatted tsfresh-black/tsfresh/feature_extraction/extraction.py
reformatted tsfresh-black/tsfresh/feature_selection/significance_tests.py
reformatted tsfresh-black/tsfresh/scripts/run_tsfresh.py
reformatted tsfresh-black/tsfresh/scripts/test_timing.py
reformatted tsfresh-black/tsfresh/feature_extraction/data.py
reformatted tsfresh-black/tsfresh/scripts/measure_execution_time.py
reformatted tsfresh-black/tsfresh/transformers/feature_augmenter.py
reformatted tsfresh-black/tsfresh/feature_extraction/settings.py
reformatted tsfresh-black/tsfresh/transformers/per_column_imputer.py
reformatted tsfresh-black/tsfresh/utilities/profiling.py
reformatted tsfresh-black/tsfresh/utilities/string_manipulation.py
reformatted tsfresh-black/tsfresh/transformers/relevant_feature_augmenter.py
reformatted tsfresh-black/tsfresh/utilities/distribution.py
reformatted tsfresh-black/tsfresh/utilities/dataframe_functions.py
reformatted tsfresh-black/tests/units/utilities/test_dataframe_functions.py
reformatted tsfresh-black/tests/units/feature_extraction/test_feature_calculations.py
reformatted tsfresh-black/tsfresh/feature_extraction/feature_calculators.py
All done! ✨ 🍰 ✨
50 files reformatted, 21 files left unchanged.
```

I have not created a new pull request yet. First, please have a look at this commit which includes all the changes from black:
https://github.com/mendel5/tsfresh-black/commit/4a037cf114dfe94a55532bd6bce699d04d0f1411

What do you think?

**Comment by MaxBenChrist** [comment]
> What do you think? Do you like it?

I only had a glimpse on it, the style after reformating actually looks nicer to me, would be in favor of merging

**Comment by mendel5** [comment]
> I only had a glimpse on it, the style after reformating actually looks nicer to me, would be in favor of merging

Thanks for your feedback. I will close this pull request ( https://github.com/blue-yonder/tsfresh/pull/858 ) and open a new, clean one for the tsfresh+black changes.

**Comment by nils-braun** [comment]
I also like it ;-) and I am glad we could finally also convince @MaxBenChrist :-D
Thanks @mendel5  for your work!

**Comment by mendel5** [comment]
> I also like it ;-) and I am glad we could finally also convince @MaxBenChrist :-D

:partying_face: 

> Thanks @mendel5 for your work!

Thank you :)

**Comment by mendel5** [comment]
New pull request for tsfresh+black is here:
- https://github.com/blue-yonder/tsfresh/pull/871

Original issue:
- https://github.com/blue-yonder/tsfresh/issues/820

**Pull request closed without merging**
