### PR TITLE
Improve performance with Numpy's sum function

### PR DESCRIPTION
**Pull request by koho**
The `change_quantiles` function need to sum the bool index array. Currently it's using the builtin `sum` function. However, NumPys `np.sum` will be faster on arrays.

I ran some test on it.
```python
import timeit
stmt = """change_quantiles(np.random.rand(300000) * 1000, 0.1, 0.2, False, 'mean')"""
print(timeit.timeit(stmt=stmt, setup='import numpy as np;from tsfresh.feature_extraction.feature_calculators import change_quantiles', number=1))
```
With the builtin `sum` function it takes 0.5s, while NumPys `np.sum` takes only 0.02s.

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
Hi @koho, can you merge the current master so we see that all tests pass? Then we can merge this into master. 👍

**Comment by dbarbier** [comment]
Hello @koho there is another instance of `sum` which could be replaced by `np.sum` in `index_mass_quantile`, maybe you could fix it too?

**Comment by dbarbier** [comment]
Thanks @koho for your quick reply.  @MaxBenChrist These changes are really trivial, could you please review this PR?  These changes provide a nice speedup with `default_fc_parameters=EfficientFCParameters()`.

**Comment by nils-braun** [comment]
Nice, thanks for the fix and sorry for the very long time to merge it!

**Pull request merged**
