### PR TITLE
Fixes issue #1073: Updated setup.cfg to require newer scipy version

### PR DESCRIPTION
**Pull request by Sarius2009**

### CODE REVIEW

**Review by nils-braun — APPROVED** [review]
Thanks!

**Comment by nils-braun** [comment]
@Sarius2009 - it seems there is no such version for older python versions

**Comment by Sarius2009** [comment]
> @Sarius2009 - it seems there is no such version for older python versions

Yes, scipy 1.14 requires at least python 3.10

**Comment by nils-braun** [comment]
Can you adjust the PR so that your lower limit only applies in this case? tsfresh is also compatible with older versions of python

**Comment by Sarius2009** [comment]
I think I did, hopefully correctly

**Review by nils-braun — APPROVED** [review]
👍

**Pull request merged**
