### PR TITLE
moved imputing out of the loop

### PR DESCRIPTION
**Pull request by MaxBenChrist**
This would be the easiest solution to move the imputing out of the loops where the id chunks are aggregated.

What do you think?

### CODE REVIEW

**Comment by nils-braun** [comment]
I thought there would be a reason to have this in the code before the concationating, because we would impute too much if we do this afterwards - but I can not remember the exact reason. I just remember that we did have the discussion before. Is your new solution faster than the old one or why did you do this?

**Comment by MaxBenChrist** [comment]
My solution should be slower. 

I think the motivation was that when you impute on chunks you can start imputing before having the whole column.

**Comment by MaxBenChrist** [comment]
So, @nils-braun @jneuff, can we merge this?

**Comment by nils-braun** [comment]
Sorry to ask again, but: why do we need this at all?

**Comment by MaxBenChrist** [comment]
I dont understand your question. Are you referring to the imputing?

**Comment by nils-braun** [comment]
No, I just wanted to know why we need your changes at all :-) Because if it does not give more features and make things slower... ;-)

**Pull request merged**
