### PR TITLE
Issue #147

### PR DESCRIPTION
**Pull request by moritzgelb**
Fix for issue #147 like recommended [here](http://docs.python-guide.org/en/latest/writing/logging/).

### CODE REVIEW

**Comment by nils-braun** [comment]
Why did you commit also the other things not related to this issue?

**Comment by nils-braun** [comment]
Otherwise I am fine with this

**Comment by MaxBenChrist** [comment]
Hi Moritz, 

if I got your changes right, under your changes the custom behavior is that if the user is not specifying an logging handler, tsfresh drops all logs... am I right?

**Comment by nils-braun** [comment]
I do think this is reasonable for the non error logs

**Comment by moritzgelb** [comment]
@nils-braun the first four commits were a mistake... I'll make a new pull request. 
@MaxBenChrist yes. The user can then specify the log level by something like: ```import logging
logging.basicConfig(level=logging.INFO)```

**Comment by nils-braun** [comment]
You could just have reverted the commits (because the branch will be squanshed anyways) - but never mind.

**Pull request closed without merging**
