### PR TITLE
Minimal feature extractor settings

### PR DESCRIPTION
**Pull request by nils-braun**
This is a first draft for #21 open for discussion.

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
I really like the usage of the @set_property decorator to mark feature calculator as basic.

We could also use this property to mark a feature as computational expensive. (like the cwt and fourier stuff)

**Comment by MaxBenChrist** [comment]
I vote for merging this in

**Comment by MaxBenChrist** [comment]
We could probably reference this MinimalFeatureExtractionSettings object somewhere in the documentation

**Comment by jneuff** [comment]
Really good idea setting the properties on the calculators. We could come up with a threshold to denote all of them with either expensive or cheap. However, I'd say 'minimal' is not the best choice for a property denoting cheap calculators.

We should come up with the threshold (n milliseconds on some reference timeseries on average hardware) and a naming scheme. The question is, do we want to merge it in now as it is and change later or merge it after we have come up with a criteria and naming scheme?

As the minimal FeatureSettings object is quite useful, I'm for a merge now. Breaking the property naming scheme later should be OK, maybe we can add a comment, that the naming is due to change.

**Comment by MaxBenChrist** [comment]
I would merge this now and open an issue for the naming scheme. Or do you already have something in mind to replace "minimal" ? Maybe "complexity_low"?

**Comment by nils-braun** [comment]
I also do not like the name and your proposal @jneuff to have a continuous number (in this case the runtime on a standardized machine) is very good. The problem is only, that we have to define this standardized machine and this  will be hard (because not all our contributors have access to the same machine). Another approach may be to have tree levels of complexity without the need to "measure".

This would then be probably another pull-request, but if you have a better name immideately, I can edit this PR now.

**Comment by MaxBenChrist** [comment]
I think it is fine as it is. I merge it and open a new issue regarding the naming

**Pull request merged**
