### PR TITLE
added security parameter for dask

### PR DESCRIPTION
**Pull request by jontis**
from distributed.security import Security
sec = Security(tls_ca_file='./dask-ca.pem', tls_client_cert='./dask-cert.pem', tls_client_key='./dask-key.pem', require_encryption=True)
Distributor = ClusterDaskDistributor(address="tls://ip_adress_or_url:8786", security=sec)

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
I think it would make more sense to expose all [distributed.Client](https://distributed.dask.org/en/latest/api.html?highlight=client#distributed.Client) arguments as kwargs.

**Comment by nils-braun** [comment]
@jontis Do you want to add the `kwargs`?

**Comment by jontis** [comment]
> @jontis Do you want to add the `kwargs`?

Not sure of the best way to do that in the most transparent way. 
I'm leaning towards for clarity
def __init__(self, address=None, **kwargs)

from distributed import Client
self.client = Client(address=address, **kwargs)

But it could as well be
def __init__(self, **kwargs)

from distributed import Client
self.client = Client(**kwargs)

Opinions?
@MaxBenChrist

**Comment by nils-braun** [comment]
Yes, I would also keep the address argument separate

**Pull request closed without merging**
