### PR TITLE
Parallel p values

### PR DESCRIPTION
**Pull request by nils-braun**
Related to #35

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
hey nils, have you seen the changes I made in 7a21b5e05fff2917aad8d7bcd753eff976b1c6df ? 

I think they are not yet incorporated in this pr?

**Comment by nils-braun** [comment]
They are, I have merged master into the PR and your new unittest changes are also in (and are still running :-) ). However, it seems I should include some more unittests to increase the coverage again.

**Comment by MaxBenChrist** [comment]
We can use our existing unit tests and let them point to `_calculate_p_value` or not?

**Comment by MaxBenChrist** [comment]
I am also working on increasing the coverage, see for example #79

**Comment by nils-braun** [comment]
Actually I have seen that coverage is a bit wrong here, as I do not decrease the coverage, but because I had to wrap the function _calcuate_p_values into a partial function, coverage does not seems to recognize the unittests actually call this function (at least twice). How should we fix this?

**Comment by MaxBenChrist** [comment]
cant we let the unit test target the _calcuate_p_values function directly?

**Comment by MaxBenChrist** [comment]
perfect, can I merge?

**Comment by nils-braun** [comment]
I do think so :-)

**Comment by MaxBenChrist** [comment]
what do you think of taking half the cores as number of processes?

**Comment by MaxBenChrist** [comment]
or all

**Comment by nils-braun** [comment]
Do you think we should make multiprocessing the default or better give hints in cases the calculation is too slow in the documentation? Using more than one core by default is - lets say - maybe a bit unexpected?

**Comment by nils-braun** [comment]
But I may be a bit too pessimistic - I think going the way you said (setting it to number of cores by default) is good. I was just thinking on batch-systems, where you may be not allowed to use more than one core... But I think this is not our main application field :-)

**Comment by MaxBenChrist** [comment]
You already set the default to 2 jobs in the feature selection settings, don't you?

I think number of cores/2 should be fine :)

**Comment by MaxBenChrist** [comment]
or all :D

**Comment by nils-braun** [comment]
Yes, my comment was more of a general reason :-) But I think just using all CPUs is fine ;-)

**Comment by MaxBenChrist** [comment]
travis stalled again. 

Just a wild guess, but maybe cpu_count() returns the number of physical cpus, even though the travis vm has only access to 1-2?

**Comment by MaxBenChrist** [comment]
after you solved that cpu issue and merged it with the current master, we can have a versioning jump to 0.1.3 :)

**Comment by nils-braun** [comment]
Perfect, I will solve this when my network connection is a bit more stable again and I can access travis a bit faster...

**Comment by nils-braun** [comment]
I have now added an override shell environment variable which is set to 1 for travis. I think this should work well.

**Comment by MaxBenChrist** [comment]
Yes, we could also directly use the TRAVIS enviroment variable. 

see https://docs.travis-ci.com/user/environment-variables/

**Comment by nils-braun** [comment]
Yes, this is possible, but I think is is more "general" to have a setting for the number of used CPUs. For example, when the number of each used CPU costs (e.g. on batch farms), you probably want to have a setting for this...

**Pull request merged**
