### PR TITLE
Use the selected features for multi-class classification in human_activity_recognition_multi_class_example.ipynb

### PR DESCRIPTION
**Pull request by sdimi**
I noticed that although you select features for X_train, those features are never actually passed to X_train and X_test. I added two lines of code that find the intersection of selected features with the original ones and also trained the classifier with those new dataframes.

`X_train_filtered = X_train[np.intersect1d(X_train.columns, list(relevant_features))]
X_test_filtered = X_test[np.intersect1d(X_test.columns, list(relevant_features))]`

### CODE REVIEW

**Comment by sdimi** [comment]
Any hints on how to pass the checks?

**Comment by MaxBenChrist** [comment]
Hi @sdimi, thanks for the pr.

Our build is broken atm due to the `LocalDaskDistributorTestCase.test_local_dask_cluster_extraction` unit test that is not related to this pr.

**Comment by sdimi** [comment]
It should be ok now.

**Comment by MaxBenChrist** [comment]
Thx!

**Pull request merged**
