### PR TITLE
Sampleentropy

### PR DESCRIPTION
**Pull request by mynameisvinn**
@MaxBenChrist one more try wrt https://github.com/blue-yonder/tsfresh/issues/50! made a couple of modifications per your comments (xrange/range, 1d arrays, etc...)

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
You dont have to close pull requests, if you push commits to the branch, github will renew the pr with the latest changes.

**Comment by MaxBenChrist** [comment]
Have you checked the unit tests locally? (`python setup.py test`), it seems that some are failing :-/

**Comment by MaxBenChrist** [comment]
https://travis-ci.org/blue-yonder/tsfresh/jobs/178354321

**Comment by mynameisvinn** [comment]
@MaxBenChrist i might be stuck. unit tests are passing locally but not remote. do you think it's because i need to modify test_settings.py?

**Comment by MaxBenChrist** [comment]
Oh no, we again have a merge conflict. Can you resolve that? I will look into the testing issues afterwards

**Comment by MaxBenChrist** [comment]
While working on another issue, i found several bugs in the unit tests. I fixed them and merged them into the master branch.

I would suggest that you merge the master into you branch. Maybe my fixes will also fix your branch. If not, I will look into that.

**Comment by mynameisvinn** [comment]
success!

**Comment by MaxBenChrist** [comment]
Awesome work @mynameisvinn!

**Pull request merged**
