### PR TITLE
Feature/pep8

### PR DESCRIPTION
**Pull request by nils-braun**
I know. This is the PR basically everyone hates.

But, for a modern python package we should also comply to pep8, so I added a github action to check exactly this + some settings (line length = 120).

I also pep8-ified everything, which means we have a large PR but *no changes except whitespace and alike*.
Tests will hopefully show that :-)

### CODE REVIEW

**Comment by dbarbier** [comment]
Another option is to use https://github.com/psf/black, it makes life easier IMHO.

**Comment by nils-braun** [comment]
I guess in the end it boils down to a matter of taste and I (personally) do not like the black decisions that much :man_shrugging: 
But of course, if people like it - I have no strong objections :-)

**Comment by nils-braun** [comment]
My suggestion: lets start with that (which is "easier" to digest) and see how people like it.
And then move to black maybe later.

**Comment by dbarbier** [comment]
Feel free to merge it when it is ready, I will take care of rebasing my branches.

**Comment by MaxBenChrist** [comment]
I used flake8 and pylint in the past. Pylint is super aggressive. Flake8 was nice. We could add it to the travis build?

**Comment by nils-braun** [comment]
This PR adds a github action (which is the CI tool of github) to do a pycodestyle check (which is exactly pep8 with some additional 120 column size setting).

**Comment by nils-braun** [comment]
@MaxBenChrist Any more thoughts or can I merge?
I want to merge this as quickly as possible because it affects so many other PRs...

**Pull request merged**
