### PR TITLE
Fix docstring of c3

### LINKED ISSUE #585: Missing terms on C3 linearity check inplementation
Good day sir. I've been testing your library for feature selection and have been excited with the ideas presented. However, while scanning through the docummentation of the C3 feature calculator I noticed an error on the algorythm. While you present it as a mean of the lag operator in the form of "E[L^2(X)^2*L(X)*X]", while coding there's a missing square on the formulation. I attached some examples I tried to check if I wasn't mistake. Hope it helps! Thank you very much for your hard work!

1. Windows
2. Tsfresh version 0.12.0
3. x = pd.Series([1, 1, 6, 9, 5, 4, 1, 2])
4. 
lag = 2
np.mean((_roll(x, 2 * -lag) * _roll(x, -lag) * x)[0:(n - 2 * lag)])
np.mean((x**2) * x.shift(periods=lag) * x.shift(periods = 2*lag))

5. From the formulation I was expecting that, for a simple example like the series t, the resulting value would be 117 but, instead got 42. I compared it with my own implementation of the formula, which I thought was somewhat clearer. Hope you can check it and, if it's wrong, fix it. 

Thank you very much!

### PR DESCRIPTION
**Pull request by dbarbier**
There were two issues:
 * sum index should start from 1 and not 0
 * x[i+2*lag] should not be squared

Fix #585.

### CODE REVIEW

**Comment by dbarbier** [comment]
The referenced paper does not look very clear to me, please carefully review these changes.

**Comment by nils-braun** [comment]
Sorry, I can also not answer as I am not an expert in the feature either. Clear thing for @MaxBenChrist ;-)

**Comment by MaxBenChrist** [comment]
We can merge this. You are correct, thank you. 

There are some other feature calculators where the index starts with i=0, you want to change them to i=1 as well?

@nils-braun the paper should be accessible to you as its from a physics department ;)

**Comment by nils-braun** [comment]
I am not in a physics department anymore ;-)

**Pull request merged**
