### PR TITLE
Feature/528 allow newest pandas version

### PR DESCRIPTION
**Pull request by nils-braun**
This builds on top of #562 and fixes the two unit tests.

It also does not require the newest version of pandas, but only to not be 0.24.*

PS: we should really fix the .travis.yaml, I have the strong feeling we are not doing this very optimally... I especially do not like the specification of the versions. Will tackle this later.

@dbarbier Are you fine with this?

### CODE REVIEW

**Comment by nils-braun** [comment]
This should fix #528

**Comment by dbarbier** [comment]
> @dbarbier Are you fine with this?

@nils-braun Sure, thanks a lot!

**Comment by dbarbier** [comment]
@nils-braun Failure is caused by a change in pandas 0.25.3, pd.melt now calls np.ravel, and quite surprisingly `np.ravel(['index', 1])` returns `array(['index', '1'], dtype='<U5')`, and pd.melt complains that there is no column named `str(1)`.  One might argue that this is a pandas bug, but on the other hand I am not sure whether mixing character and numeric column names is well supported, thus I suggest to use a numeric name for index if columns have numeric names.

**Comment by nils-braun** [comment]
Yes, thanks for pointing out. I did see it yesterday evening but could not fix it before going to bed.

I will create an issue on the pandas repo nevertheless, but I guess you are right: we should fix it also from our side.

**Comment by nils-braun** [comment]
(hopefully this will all go away once https://github.com/pandas-dev/pandas/pull/28859 is finished)

**Comment by Froskekongen** [comment]
Would it be possible to do a new release once this PR is merged?

**Comment by dbarbier** [comment]
Hi @nils-braun do you have any idea why travis builds are failing?

**Comment by dbarbier** [comment]
Got it, pandas 0.25 requires python >= 3.5.3 https://pandas.pydata.org/pandas-docs/stable/install.html#python-version-support
I can confirm that everything works fine with python 3.5.3.

**Comment by Rictus** [comment]
Thank you for this work!

**Pull request merged**
